### PR TITLE
More factoring of the cleanup code for tac_connect_single

### PR DESCRIPTION
**Pull request by pprindeville**
Commit 654b79e removed a very similar check, but with the new
common exit strategy for this function, it is in fact possible to
have fd be set without having copied fd into retval (i.e. retval
still being set to an error value, which is negative).

### CODE REVIEW

**Comment by pprindeville** [comment]
Per @daveolsen53's suggestion on another branch.

**Comment by pprindeville** [comment]
Okay, weird... not sure why the CI build failed. Nothing I touched should have changed that...

**Comment by daveolson53** [comment]
If fd isn't copied to retval, then it's leaked, so that would be a bug, which is what I think you are saying, and agreeing with my proposal on the other comment. (Although it would be weird to leave it in the FD_SET).  Hmmm.  A bit more complex.   Probably not a big issue, because a closed fd won't have an effect, it would only have an effect if the fd gets re-used later, and we'd have  a "spurious" wakeup.

**Comment by pprindeville** [comment]
> (Although it would be weird to leave it in the FD_SET). Hmmm. A bit more complex.

Is it?  `readfs` and `writefs` are locals to `tac_connect_single()`, so leaving the bit for `fd` set when we exit the function should be harmless.

**Comment by daveolson53** [comment]
Philip Prindeville <notifications@github.com> wrote:

>     (Although it would be weird to leave it in the FD_SET). Hmmm. A bit more
>     complex.
> 
> Is it? readfs and writefs are locals to tac_connect_single(), so leaving the
> bit for fd set when we exit the function should be harmless.

Oh, of course.  No issue, then.

Dave Olson
olson@cumulusnetworks.com

**Comment by jeroennijhof** [comment]
I was just configuring ci so that can be ignored. Thanks!

**Pull request merged**
