### PR TITLE
Retire logwtmp() in favor of POSIX pututxline()

### PR DESCRIPTION
**Pull request by pprindeville**
Favor POSIX functions for portability wherever possible.

### CODE REVIEW

**Comment by pprindeville** [comment]
@vollkommenheit @daveolson53 Please test this PR under OS X.

**Comment by vollkommenheit** [comment]
Built successfully with the fix-logwtmp branch.

**Comment by pprindeville** [comment]
> Built successfully with the fix-logwtmp branch.

Thanks, but can you run it (`tacc`) without the `-w` flag and let me know if `wtmp` is being updated properly?  `who` and `last` should help with this.

**Comment by daveolson53** [comment]
I can't even compile this branch on OSx 10.13.2 (with 'auto.sh ; ./configure; make)'

It fails as:

libtool: compile:  gcc -DHAVE_CONFIG_H -I. -Wall -Wextra -Werror -I ./libtac/include -I ./libtac/lib -g -O2 -MT pam_tacplus_la-pam_tacplus.lo -MD -MP -MF .deps/pam_tacplus_la-pam_tacplus.Tpo -c pam_tacplus.c  -fno-common -DPIC -o .libs/pam_tacplus_la-pam_tacplus.o
pam_tacplus.c:526:7: error: explicitly assigning value of variable of type 'pam_handle_t *' (aka 'struct pam_handle *') to itself [-Werror,-Wself-assign]
        pamh = pamh;
        ~~~~ ^ ~~~~
pam_tacplus.c:527:8: error: explicitly assigning value of variable of type 'int' to itself [-Werror,-Wself-assign]
        flags = flags;                          /* unused */
        ~~~~~ ^ ~~~~~
pam_tacplus.c:552:8: error: explicitly assigning value of variable of type 'int' to itself [-Werror,-Wself-assign]
        flags = flags;                          /* unused */
        ~~~~~ ^ ~~~~~
pam_tacplus.c:722:8: error: explicitly assigning value of variable of type 'int' to itself [-Werror,-Wself-assign]
        flags = flags;                          /* unused */
        ~~~~~ ^ ~~~~~
pam_tacplus.c:735:8: error: explicitly assigning value of variable of type 'int' to itself [-Werror,-Wself-assign]
        flags = flags;                          /* unused */
        ~~~~~ ^ ~~~~~
5 errors generated.
make[1]: *** [pam_tacplus_la-pam_tacplus.lo] Error 1
make: *** [all] Error 2

olson 12:59_pam_tacplus.536 gcc --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 9.0.0 (clang-900.0.39.2)
Target: x86_64-apple-darwin17.3.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

I can get past that by "CFLAGS=-Wno-error=self-assign ./configure"

If I run tacc with -w, it completes successfully 

If I run tacc without -w, I get this abort:
(lldb) bt
* thread #1, stop reason = signal SIGABRT
  * frame #0: 0x0000000100036216 dyld`__abort_with_payload + 10
    frame #1: 0x0000000100035b88 dyld`abort_with_payload_wrapper_internal + 89
    frame #2: 0x0000000100035bb5 dyld`abort_with_payload + 9
    frame #3: 0x0000000100009482 dyld`dyld::halt(char const*) + 354
    frame #4: 0x000000010000c533 dyld`dyld::_main(macho_header const*, unsigned long, int, char const**, char const**, char const**, unsigned long*) + 8004
    frame #5: 0x00000001000063d4 dyld`dyldbootstrap::start(macho_header const*, int, char const**, long, macho_header const*, unsigned long*) + 453
    frame #6: 0x00000001000061d2 dyld`_dyld_start + 54

I do have pututxline in /usr/include/utmpx.h, and debugging shows we are trying to use pututxline, but it dies at this line, just before the setutxtmp()
   xstrcpy(utmpx.ut_id, tty, sizeof(utmpx.ut_id));

I'm using -y ttys020 ; for some reason, the xstrcpy is doing something wrong (sizeof utmpx.ut_id == 4 for my OSx version).   

If I use -y abc (or other 3 char line strings) then it works without -w.   I haven't debugged further.

**Comment by pprindeville** [comment]
> I can get past that by `"CFLAGS=-Wno-error=self-assign ./configure"`

@daveolson53 That's a known issue.  I'm just waiting for a review on PR #106 to merge that.

**Comment by pprindeville** [comment]
@daveolson53 What does your debugger show as being the value of `tty`?

**Comment by daveolson53** [comment]
I printed it with printf, because I was having gdb symbol problems,   It was the string that I passed in via -y (ttys020 in the original case, abc in the revised case with the nonsense string).  Not an issue of a corrupted argument string.

Looking at xstrcpy()  in xalloc.c (I hadn't done that in a while), we have this:

    if (strlen(src) >= dst_size) {
        TACSYSLOG(LOG_ERR, "xstrcpy(): argument too long, aborting");
        abort();
    }

Since almost all tty arguments are going to be more than 4 characters, either xstrcpy semantics need to change (probably not), or using the tty as the ID string we need to truncate the string before calling xstrcpy, or just use snprintf, or some other similar method; we can't just pass it as is to xstrcpy

**Comment by pprindeville** [comment]
Okay, I've tweaked the PR.  Please refetch and test.

**Comment by daveolson53** [comment]
Philip Prindeville <notifications@github.com> wrote:

> Okay, I've tweaked the PR. Please refetch and test.

Yes, that does it, and using strncpy instead of xstrcpy will fix it for
even longer names (I verified that), although we will still have issues
with xstrcpy in other places in tacc.c

In general, using xstrcpy in tacc is always going to have these kinds
of problems, and it probably should be completely replaced with
checks and warnings.

But I guess it's good enough, for a test program.  It wouldn't hurt
to add to the notes on tacc that it suffers from "strings too long lead
to abort".

Thanks for working this through.

Dave Olson
olson@cumulusnetworks.com

**Comment by pprindeville** [comment]
I've merged the `_Unused` fix to `master`, btw.

**Comment by pprindeville** [comment]
@daveolson53 Can you please post output from `who` showing logging from `tacc` (without `-w`)?  Thanks.

**Comment by daveolson53** [comment]
Philip Prindeville <notifications@github.com> wrote:

> @daveolson53 Can you please post output from who showing logging from tacc
> (without -w)? Thanks.

Because tacc cleans up as part of running, you can't just run who
afterwards.   I added it as 'system("who")' with an echo, before and
after the cleanup.

As part of that, I also ran last, and there's a problem, the info used
by 'last' doesn't get cleaned up.   Apparently modern OSx stores the
last info in an apple-specifc log file.   I didn't track down how to
clean that up.


Anyway, here's an example session:

========
.libs/tacc -TRA -u olsont -p XXXX -s aaa-testing -r olson -k XYZZY -S ssh -P ip -y console -L -r ttys020
Authentication OK
Authorization OK: (Service granted)
Accounting: START OK
Accounting: STOP OK
Prior to removing user
olsont   console  Jan  3 14:14 	(dialup)
olson    console  Dec 13 10:13
olson    ttys000  Dec 13 10:16
olson    ttys001  Dec 15 11:16
olson    ttys002  Dec 13 10:16
olson    ttys003  Dec 13 10:16
olson    ttys004  Dec 13 10:16
olson    ttys005  Dec 13 10:16
olson    ttys007  Dec 13 10:16
Cleaned up utmpx
After removing user
olson    console  Dec 13 10:13
olson    ttys000  Dec 13 10:16
olson    ttys001  Dec 15 11:16
olson    ttys002  Dec 13 10:16
olson    ttys003  Dec 13 10:16
olson    ttys004  Dec 13 10:16
olson    ttys005  Dec 13 10:16
olson    ttys007  Dec 13 10:16

olson 14:14_pam_tacplus.584 last | head
olsont    console  dialup           Wed Jan  3 14:14   still logged in
olsont    console  dialup           Wed Jan  3 14:12   still logged in
olsont    console  dialup           Wed Jan  3 13:54   still logged in
olson     ttys006                   Wed Jan  3 13:05 - 13:05  (00:00)
olsont    console  dialup           Wed Jan  3 12:00   still logged in
========

Dave Olson
olson@cumulusnetworks.com

**Comment by pprindeville** [comment]
> Apparently modern OSx stores the last info in an apple-specifc log file. I didn't track down how to clean that up.

I'll hold the fix back.  If you figure this out, I'll incorporate it.

The glibc-2.25 man pages for `pututxline(3)` are inaccurate so of limited help.

**Comment by daveolson53** [comment]
Philip Prindeville <notifications@github.com> wrote:

>     Apparently modern OSx stores the last info in an apple-specifc log file. I
>     didn't track down how to clean that up.
> 
> I'll hold the fix back. If you figure this out, I'll incorporate it.
> 
> The glibc-2.25 man pages for pututxline(3) are inaccurate so of limited help.

It's not a problem with the way pututxline is used.  'last' still shows
the user even if I rename /var/run/utmpx.   It looks like the
getlastlogx() routines allow you to get the list (defined in utmpx.h on
my Mac), but I don't see a corresponding library call to update it.

Or you can walk the list with setutxent_wtmp(), getutxent_wtmp(),
endutxent_wtmp(), but again, I don't see a 'put' or other update
entry point. 

It's no worse than using the logwtmp() method, that has the same
problem.  So I'd go ahead and pull the change, and just note the
issue in the commit message, and a comment in the code.

Maybe somebody will see one or the other, and suggest how to
update the lastlog info.


Dave Olson
olson@cumulusnetworks.com

**Comment by pprindeville** [comment]
@daveolson53 What happens on linux if you put the `system("who");` back in and run it?

**Comment by daveolson53** [comment]
Philip Prindeville <notifications@github.com> wrote:

> @daveolson53 What happens on linux if you put the system("who"); back in and
> run it?

who is correct.  /var/log/wtmp isn't updated at all, and therefore
'last' shows nothing about the run.

==========
./tacc -TRA -u olsont -p XXXX -s aaa-testing -r redxp-02 -k XYZZY -S ssh -P ip -y ttys0400 -L -r ttys01
Authentication OK
Authorization OK: (Service granted)
Accounting: START OK
pututxline case, ut_id is s040, ut_line is ttys0400, len 8, passed in
(s0400), idlen=4
Accounting: STOP OK
after do_account cleanup
Prior to removing user
root     ttyS0        2018-01-04 21:03
olsont   ttys0400     2018-01-05 00:05 (dialup)
Cleaned up utmpx
After to removing user
root     ttyS0        2018-01-04 21:03
==========

Dave Olson
olson@cumulusnetworks.com

**Comment by pprindeville** [comment]
@daveolson53 Thanks for testing that.  Merged.

**Pull request merged**
