### PR TITLE
Exit tac_connect_single consistently via bottom of function

### PR DESCRIPTION
**Pull request by pprindeville**
This is so that tracing is always the same, even when exceptions occur.

### CODE REVIEW

**Comment by jeroennijhof** [comment]
Thank you for your pull requests but lets try not using goto for this. All goto should be replaced and will be replaced in existing code base /cc @kravietz

**Comment by daveolson53** [comment]
jeroennijhof <notifications@github.com> wrote:

> Thank you for your pull requests but lets try not using goto for this. All goto
> should be replaced and will be replaced in existing code base /cc @kravietz

Why do we want to get rid of gotos?  Not for purist reasons, I hope?

For this kind of code (in this change), it is much cleaner to have a
common exit point than a long series of returns, some of which miss
cleanup actions?  We've all fixed cases where a cleanup action got
missed.

Restructuring code like this to have a common exit, and not use gotos is
certainly possible, but much less readable, and in my opinion, harder to
maintain.

I've done some restructuring for common exits, some with goto, some
without, depending on what the code is doing.

I'll get that up on github "soon" (really...) so people can look
at it overall, and then submit it as at least a few separate pull
requests.

Dave Olson
olson@cumulusnetworks.com

**Comment by pprindeville** [comment]
See PR #67 as an alternative approach.

**Comment by jeroennijhof** [comment]
I don't want to be that guy and I agree with you @daveolson53 but still I'm dying a bit inside... :joy:

**Pull request merged**
